language: java
jdk:
  - openjdk8

branches:
  only:
    - master


# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r springbook *
  - mkdir -p deploy
  - mv springbook.zip deploy/springbook.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #travis setting에서 설정한 값
    secret_access_key: $AWS_SECRET_KEY #travis setting에서 설정한 값
    bucket: springbook-build #S3의 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed : true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ohhyun1948@gmail.com
